#!/usr/bin/env python3
"""Generate a report of current-team profile pages with missing or incomplete lab dates."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PEOPLE_PAGE = ROOT / "people" / "index.html"
REPORT_PATH = ROOT / "docs" / "missing-team-lab-dates.md"

PROFILE_LINK_RE = re.compile(r'<a href="\.\./([^/]+)/" class="person-link-wrap">', re.IGNORECASE)
NAME_RE = re.compile(r"<h1>(.*?)</h1>", re.IGNORECASE | re.DOTALL)
ROLE_RE = re.compile(r'<p class="role">(.*?)</p>', re.IGNORECASE | re.DOTALL)
LAB_DATES_RE = re.compile(r'<p class="profile-lab-dates"><strong>Lab dates:</strong>\s*(.*?)</p>', re.IGNORECASE | re.DOTALL)
TAG_RE = re.compile(r"<[^>]+>")


def strip_tags(text: str) -> str:
    return TAG_RE.sub("", text).replace("&amp;", "&").strip()


def is_pi_role(role_text: str) -> bool:
    role = role_text.lower()
    return "professor" in role and "microbiology" in role


def collect_team_profiles() -> list[tuple[str, Path]]:
    html = PEOPLE_PAGE.read_text(encoding="utf-8")
    slugs = []
    for slug in PROFILE_LINK_RE.findall(html):
        if slug not in slugs:
            slugs.append(slug)
    return [(slug, ROOT / slug / "index.html") for slug in slugs]


def inspect_profile(profile_file: Path) -> tuple[str, str, str | None]:
    html = profile_file.read_text(encoding="utf-8")
    name_match = NAME_RE.search(html)
    role_match = ROLE_RE.search(html)
    dates_match = LAB_DATES_RE.search(html)

    name = strip_tags(name_match.group(1)) if name_match else profile_file.parent.name.replace("-", " ").title()
    role = strip_tags(role_match.group(1)) if role_match else ""
    lab_dates = strip_tags(dates_match.group(1)) if dates_match else None

    return name, role, lab_dates


def missing_reason(lab_dates: str | None) -> str | None:
    if not lab_dates:
        return "Add lab dates line"
    normalized = lab_dates.replace("—", "–")
    if re.fullmatch(r"\d{4}\s*[–-]\s*Present", normalized, flags=re.IGNORECASE):
        return "Start month + year"
    return None


def build_report(rows: list[dict[str, str]]) -> str:
    lines = [
        "# Missing Team Lab Dates",
        "",
        "Generated by `scripts/report_missing_team_dates.py`.",
        "",
    ]

    if not rows:
        lines.extend([
            "All current team profiles include lab dates with month+year start values where currently known.",
            "",
            "| Name | Profile file | Current lab dates string | Missing info needed |",
            "| --- | --- | --- | --- |",
            "| None | — | — | — |",
            "",
        ])
        return "\n".join(lines)

    lines.extend([
        "| Name | Profile file | Current lab dates string | Missing info needed |",
        "| --- | --- | --- | --- |",
    ])

    for row in rows:
        lines.append(
            f"| {row['name']} | `{row['profile']}` | {row['lab_dates']} | {row['reason']} |"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    missing_rows: list[dict[str, str]] = []

    for slug, profile_file in collect_team_profiles():
        if not profile_file.exists():
            missing_rows.append(
                {
                    "name": slug.replace("-", " ").title(),
                    "profile": str(profile_file.relative_to(ROOT)),
                    "lab_dates": "(profile file missing)",
                    "reason": "Add profile file",
                }
            )
            continue

        name, role, lab_dates = inspect_profile(profile_file)
        if is_pi_role(role):
            continue
        reason = missing_reason(lab_dates)
        if reason:
            missing_rows.append(
                {
                    "name": name,
                    "profile": str(profile_file.relative_to(ROOT)),
                    "lab_dates": lab_dates or "(missing)",
                    "reason": reason,
                }
            )

    report = build_report(missing_rows)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")

    print(f"Scanned {len(collect_team_profiles())} current team profiles")
    print(f"Flagged {len(missing_rows)} profile(s) with missing/incomplete lab dates")
    print(f"Wrote report: {REPORT_PATH}")


if __name__ == "__main__":
    main()
